#####################################################################################
### DeathLocation                                                                 ###
###                                                                               ###
### For bugreports and proposals join our Discord: https://discord.gg/p95cB9YQFJ  ###
###                                                                               ###
### You can find the source code at: https://github.com/Xitee1/DeathLocation      ###
#####################################################################################